import assert from 'node:assert/strict';import {chromium} from 'playwright';import path from 'node:path';import fs from 'node:fs/promises';
const shots=process.env.LOOT_SHOTS||'/tmp/loot-review';await fs.mkdir(shots,{recursive:true});const browser=await chromium.launch(),errors=[];
try{
 const p=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});p.on('pageerror',e=>errors.push(e.message));await p.route('https://fonts.googleapis.com/**',r=>r.abort());await p.addInitScript(()=>localStorage.setItem('fuwa-help-seen','{"map":1}'));await p.goto('file://'+path.resolve('index.html')+'#town');await p.waitForFunction(()=>!document.body.classList.contains('image-boot'));
 await p.evaluate(()=>{state.page='battle';state.scout=null;startBattle('ambush');B().flowEpoch=(B().flowEpoch||0)+1;B().tut=-1;render();});
 assert.equal(await p.locator('.victory-loot').count(),0);assert.equal(await p.evaluate(()=>claimBattleLoot('loot-0','fox')),false);assert.equal(await p.evaluate(()=>{const u=B().units.find(u=>u.id==='wolf'),root=document.createElement('div');root.innerHTML=StatusCard.render(u,B(),true);return !!root.querySelector('[data-gearbag] .gear-item[data-tip*="箭袋"] svg path');}),true);
 const expected=await p.evaluate(()=>{
  const b=B(),foes=b.units.filter(u=>u.side==='foe'),potion=ITEMS.find(i=>i.n==='治療藥水');
  foes[0].backpack.push(potion);foes[0].items=[potion];dropItem(foes[0],potion);
  const armed=foes.find(u=>u.weapon),dropped=armed.weapon;takeFrom(armed,dropped);b.drops=[{x:2,y:2,item:dropped,name:dropped.n,from:armed.id}];
  b.units.find(u=>u.side==='npc').weapon=ITEMS.find(i=>i.n==='巨劍');const focus=foes.find(u=>u.focus).focus;focus.quality='測試原品質';
  foes.forEach(u=>{u.hp=0;u.dead=true;});checkResult();
  window.__floor=document.getElementById('board-floor');return {focus:focus.id,stat:focus.stat,total:foes.reduce((n,u)=>n+[u.weapon,u.focus,u.armor,...u.backpack].filter(Boolean).length,0)+b.drops.length};
 });
 assert.equal(await p.locator('[data-loot]').count(),expected.total);assert.equal(await p.evaluate(()=>battleLoot().filter(r=>r.item.n==='破布衣').length),3);assert.equal(await p.evaluate(()=>battleLoot().filter(r=>r.item.n==='治療藥水').length),0);assert.equal(await p.evaluate(()=>battleLoot().filter(r=>r.source==='地面').length),1);assert.equal(await p.evaluate(()=>battleLoot().filter(r=>r.item.n==='巨劍').length),0);assert.equal(await p.locator('.loot-item').filter({hasText:'破布衣'}).locator('svg').count(),3);assert.equal(await p.locator('.loot-item').filter({hasText:'箭袋'}).locator('svg path').count()>0,true);
 await p.waitForTimeout(850);await p.screenshot({path:shots+'/list.png'});
 const choose=async id=>{if(!await p.locator('.loot-select').evaluate(el=>el.open))await p.locator('.loot-select summary').tap();await p.locator(`[data-loot-person="${id}"]`).tap();assert.equal(await p.locator('.loot-select').evaluate(el=>el.open),false);};
 const ground=await p.evaluate(()=>battleLoot().find(r=>r.source==='地面').key);await p.locator(`[data-loot="${ground}"]`).tap();await choose('wolf');await p.locator('[data-loot-to="wolf"]').tap();assert.equal(await p.evaluate(()=>B().drops.length),0);assert.equal(await p.evaluate(()=>document.getElementById('board-floor')===window.__floor),true);assert.equal(await p.evaluate(k=>claimBattleLoot(k,'wolf'),ground),false);
 const focusKey=await p.evaluate(id=>battleLoot().find(r=>r.item.id===id).key,expected.focus);await p.locator(`[data-loot="${focusKey}"]`).tap();await choose('fox');await p.locator('[data-loot-to="fox"]').tap();const stored=await p.evaluate(id=>({n:state.inv.fox.filter(x=>x===id).length,stat:itemById(id).stat,quality:itemById(id).quality,bag:B().units.find(u=>u.id==='fox').backpack.some(x=>x.id===id),equipped:B().units.find(u=>u.id==='fox').focus?.id}),expected.focus);assert.equal(stored.n,1);assert.equal(stored.stat,expected.stat);assert.equal(stored.quality,'測試原品質');assert(stored.bag);assert.notEqual(stored.equipped,expected.focus);
 const cloth=await p.evaluate(()=>battleLoot().filter(r=>!r.claimed&&r.item.n==='破布衣').map(r=>r.key));
 for(const [i,id] of ['tiger','raccoon'].entries()){await p.locator(`[data-loot="${cloth[i]}"]`).tap();await choose(id);await p.locator(`[data-loot-to="${id}"]`).tap();assert(await p.evaluate(id=>B().units.find(u=>u.id===id).backpack.some(it=>it.n==='破布衣'),id));}
 // Exact capacity is legal, a fraction over is rejected; full inventory includes a separately held focus.
 const capacity=await p.evaluate(k=>{const u=B().units.find(u=>u.id==='fox'),row=battleLoot().find(r=>r.key===k);state.magicItems ||= {};state.magicItems['loot-weight-fixture']={id:'loot-weight-fixture',type:'gear',n:'測試負重',wt:worldCapacity(u)-weightOf(u.id)-row.item.wt+.01};state.inv.fox.push('loot-weight-fixture');u.backpack.push(state.magicItems['loot-weight-fixture']);return {before:state.inv.fox.length,cap:worldCapacity(u),key:k};},cloth[2]);await p.locator(`[data-loot="${cloth[2]}"]`).tap();await choose('fox');assert.equal(await p.locator('[data-loot-to]').count(),1);assert(await p.locator('[data-loot-to="fox"]').isDisabled());assert.equal(await p.evaluate(k=>claimBattleLoot(k,'fox'),cloth[2]),false);assert.equal(await p.evaluate(()=>state.inv.fox.length),capacity.before);assert.equal(await p.locator(`[data-loot="${cloth[2]}"]`).count(),1);await p.screenshot({path:shots+'/capacity.png'});await p.evaluate(()=>{const npc=B().units.find(u=>u.side==='npc');npc.partyMember=true;npc.backpackEquip=ITEMS.find(i=>i.n==='背包');npc.backpack=[];refreshBattle();});assert.equal(await p.locator('[data-loot-person]').count(),5);assert.equal(await p.locator('[data-loot-slider]').count(),0);await p.locator('.loot-select summary').tap();await p.screenshot({path:shots+'/expanded.png'});const listBox=await p.locator('.loot-people').boundingBox();await p.mouse.move(listBox.x+listBox.width/2,listBox.y+listBox.height/2);await p.mouse.wheel(0,180);await p.waitForTimeout(200);assert(await p.locator('.loot-people').evaluate(el=>el.scrollTop>0&&el.scrollHeight>el.clientHeight&&el.getBoundingClientRect().height===132));await p.locator('.loot-people').evaluate(el=>el.scrollTop=0);const cdp=await p.context().newCDPSession(p),tx=listBox.x+listBox.width/2,ty=listBox.y+listBox.height-12;await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:tx,y:ty}]});for(let i=1;i<=5;i++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:tx,y:ty-i*18}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await p.waitForTimeout(250);assert(await p.locator('.loot-people').evaluate(el=>el.scrollTop>0));await cdp.detach();await choose(await p.evaluate(()=>B().units.find(u=>u.side==='npc').id));assert.equal(await p.locator('[data-loot-to]').getAttribute('data-loot-to'),await p.evaluate(()=>B().units.find(u=>u.side==='npc').id));await p.screenshot({path:shots+'/npc.png'});assert.equal(await p.evaluate(()=>{const npc=B().units.find(u=>u.side==='npc'),row=battleLoot().find(r=>!r.claimed&&!(B().lootPicked||[]).includes(r.key));const ok=claimBattleLoot(row.key,npc.id);return ok&&npc.backpack.includes(row.item)&&state.inv[npc.id].includes(row.item.id);}),true);await p.evaluate(()=>{B().units.find(u=>u.side==='npc').partyMember=false;refreshBattle();});assert.deepEqual(await p.evaluate(()=>B().lootPicked),await p.evaluate(k=>[k],cloth[2]));await choose('fox');
 await p.evaluate(()=>{state.magicItems['loot-weight-fixture'].wt-=.01;refreshBattle();});assert(await p.locator('[data-loot-to="fox"]').isEnabled());await choose('fox');await p.locator('[data-loot-to="fox"]').tap();assert.equal(await p.evaluate(()=>state.inv.fox.length),capacity.before+1);
 // 10-10 多選：點一下勾選、再點取消；全選／取消；整批放入；總重超過就整批不放並寫超重多少。
 {const left=await p.evaluate(()=>battleLoot().filter(r=>!r.claimed).map(r=>r.key));assert(left.length>=2);
  await p.locator(`[data-loot="${left[0]}"]`).tap();await p.locator(`[data-loot="${left[1]}"]`).tap();assert.deepEqual(await p.evaluate(()=>B().lootPicked),left.slice(0,2));assert.equal(await p.locator('.loot-item.on').count(),2);assert.match(await p.locator('.loot-instruction').innerText(),/將 2 件/);
  await p.locator(`[data-loot="${left[1]}"]`).tap();assert.deepEqual(await p.evaluate(()=>B().lootPicked),left.slice(0,1));
  await p.locator('[data-lootall]').tap();assert.equal(await p.locator('.loot-item.on').count(),left.length);assert.equal(await p.locator('[data-lootall]').innerText(),'取消');
  await p.locator('[data-lootall]').tap();assert.equal(await p.locator('.loot-item.on').count(),0);assert.equal(await p.locator('[data-loot-to]').count(),0);
  // fox 已滿載：勾兩件 → 整批拒絕，寫超重多少，什麼都沒放
  for(const k of left.slice(0,2))await p.locator(`[data-loot="${k}"]`).tap();await choose('fox');const before=await p.evaluate(()=>state.inv.fox.length);assert(await p.locator('[data-loot-to="fox"]').isDisabled());assert.match(await p.locator('.loot-load').innerText(),/→.*超重 [\d.]+ lb/);assert.equal(await p.evaluate(k=>claimBattleLoot(k,'fox'),left.slice(0,2)),false);assert.equal(await p.evaluate(()=>state.inv.fox.length),before);await p.screenshot({path:shots+'/multi-over.png'});
  // 改給嬌嬌：兩件一次放入
  await choose('tiger');const tb=await p.evaluate(()=>state.inv.tiger.length);assert.match(await p.locator('.loot-load').innerText(),/→/);await p.screenshot({path:shots+'/multi.png'});await p.locator('[data-loot-to="tiger"]').tap();assert.equal(await p.evaluate(()=>state.inv.tiger.length),tb+2);assert.deepEqual(await p.evaluate(()=>B().lootPicked),[]);assert.equal(await p.evaluate(ks=>ks.every(k=>battleLoot().find(r=>r.key===k).claimed),left.slice(0,2)),true);assert.equal(await p.evaluate(k=>claimBattleLoot(k,'tiger'),left.slice(0,2)),false);}
 const snapshot=await p.evaluate(()=>JSON.stringify(state.inv));await p.evaluate(()=>refreshBattle());assert.equal(await p.evaluate(()=>JSON.stringify(state.inv)),snapshot);assert(await p.locator('[data-loot]').count()>0);await p.locator('#afterWin').tap();assert.equal(await p.evaluate(()=>state.scene),'caravan');assert.equal(await p.evaluate(()=>JSON.stringify(state.inv)),snapshot);assert.equal(await p.locator('.victory-loot').count(),0);
 await p.evaluate(()=>{state.page='battle';startBattle('worldMimic');B().flowEpoch=(B().flowEpoch||0)+1;B().units.filter(u=>u.side==='foe').forEach(u=>{u.dead=true;u.hp=0;});checkResult();render();});assert.equal(await p.locator('[data-loot]').count(),0);assert.match(await p.locator('.victory-loot').innerText(),/沒有剩餘/);assert(await p.locator('#afterWin').isEnabled());
 assert.deepEqual(errors,[]);console.log('✓ actual 390×844 touch list→four specified backpacks, 3 identical copies, remaining gear+ground, consumed excluded, original focus identity/quality/stat, exact capacity/overweight, duplicate/repaint safe, no auto-equip, leave unwanted+caravan, empty mimic, floor DOM retained, screenshots');
}finally{await browser.close();}
