import assert from 'node:assert/strict';import {chromium} from 'playwright';import path from 'node:path';import fs from 'node:fs/promises';
const shots=process.env.LOOT_SHOTS||'/tmp/loot-review';await fs.mkdir(shots,{recursive:true});const browser=await chromium.launch(),errors=[];
try{
 const p=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});p.on('pageerror',e=>errors.push(e.message));await p.route('https://fonts.googleapis.com/**',r=>r.abort());await p.addInitScript(()=>localStorage.setItem('fuwa-help-seen','{"map":1}'));await p.goto('file://'+path.resolve('index.html')+'#town');await p.waitForFunction(()=>!document.body.classList.contains('image-boot'));
 await p.evaluate(()=>{state.page='battle';state.scout=null;startBattle('ambush');B().flowEpoch=(B().flowEpoch||0)+1;B().tut=-1;render();});
 assert.equal(await p.locator('.victory-loot').count(),0);assert.equal(await p.evaluate(()=>claimBattleLoot('loot-0','fox')),false);
 const expected=await p.evaluate(()=>{
  const b=B(),foes=b.units.filter(u=>u.side==='foe'),potion=ITEMS.find(i=>i.n==='治療藥水');
  foes[0].backpack.push(potion);foes[0].items=[potion];dropItem(foes[0],potion);
  const armed=foes.find(u=>u.weapon),dropped=armed.weapon;takeFrom(armed,dropped);b.drops=[{x:2,y:2,item:dropped,name:dropped.n,from:armed.id}];
  b.units.find(u=>u.side==='npc').weapon=ITEMS.find(i=>i.n==='巨劍');const focus=foes.find(u=>u.focus).focus;focus.quality='測試原品質';
  foes.forEach(u=>{u.hp=0;u.dead=true;});checkResult();
  window.__floor=document.getElementById('board-floor');return {focus:focus.id,stat:focus.stat,total:foes.reduce((n,u)=>n+[u.weapon,u.focus,u.armor,...u.backpack].filter(Boolean).length,0)+b.drops.length};
 });
 assert.equal(await p.locator('[data-loot]').count(),expected.total);assert.equal(await p.evaluate(()=>battleLoot().filter(r=>r.item.n==='破布衣').length),3);assert.equal(await p.evaluate(()=>battleLoot().filter(r=>r.item.n==='治療藥水').length),0);assert.equal(await p.evaluate(()=>battleLoot().filter(r=>r.source==='地面').length),1);assert.equal(await p.evaluate(()=>battleLoot().filter(r=>r.item.n==='巨劍').length),0);assert.equal(await p.locator('.loot-item').filter({hasText:'破布衣'}).locator('svg').count(),3);
 await p.waitForTimeout(850);await p.screenshot({path:shots+'/list.png'});
 const ground=await p.evaluate(()=>battleLoot().find(r=>r.source==='地面').key);await p.locator(`[data-loot="${ground}"]`).tap();await p.locator('[data-loot-to="wolf"]').tap();assert.equal(await p.evaluate(()=>B().drops.length),0);assert.equal(await p.evaluate(()=>document.getElementById('board-floor')===window.__floor),true);assert.equal(await p.evaluate(k=>claimBattleLoot(k,'wolf'),ground),false);
 const focusKey=await p.evaluate(id=>battleLoot().find(r=>r.item.id===id).key,expected.focus);await p.locator(`[data-loot="${focusKey}"]`).tap();await p.locator('[data-loot-to="fox"]').tap();const stored=await p.evaluate(id=>({n:state.inv.fox.filter(x=>x===id).length,stat:itemById(id).stat,quality:itemById(id).quality,bag:B().units.find(u=>u.id==='fox').backpack.some(x=>x.id===id),equipped:B().units.find(u=>u.id==='fox').focus?.id}),expected.focus);assert.equal(stored.n,1);assert.equal(stored.stat,expected.stat);assert.equal(stored.quality,'測試原品質');assert(stored.bag);assert.notEqual(stored.equipped,expected.focus);
 const cloth=await p.evaluate(()=>battleLoot().filter(r=>!r.claimed&&r.item.n==='破布衣').map(r=>r.key));
 for(const [i,id] of ['tiger','raccoon'].entries()){await p.locator(`[data-loot="${cloth[i]}"]`).tap();await p.locator(`[data-loot-to="${id}"]`).tap();assert(await p.evaluate(id=>B().units.find(u=>u.id===id).backpack.some(it=>it.n==='破布衣'),id));}
 // Exact capacity is legal, a fraction over is rejected; full inventory includes a separately held focus.
 const capacity=await p.evaluate(k=>{const u=B().units.find(u=>u.id==='fox'),row=battleLoot().find(r=>r.key===k);state.magicItems ||= {};state.magicItems['loot-weight-fixture']={id:'loot-weight-fixture',type:'gear',n:'測試負重',wt:worldCapacity(u)-weightOf(u.id)-row.item.wt+.01};state.inv.fox.push('loot-weight-fixture');u.backpack.push(state.magicItems['loot-weight-fixture']);return {before:state.inv.fox.length,cap:worldCapacity(u),key:k};},cloth[2]);await p.locator(`[data-loot="${cloth[2]}"]`).tap();assert(await p.locator('[data-loot-to="fox"]').isDisabled());assert.equal(await p.evaluate(k=>claimBattleLoot(k,'fox'),cloth[2]),false);assert.equal(await p.evaluate(()=>state.inv.fox.length),capacity.before);assert.equal(await p.locator(`[data-loot="${cloth[2]}"]`).count(),1);await p.screenshot({path:shots+'/capacity.png'});
 await p.evaluate(()=>{state.magicItems['loot-weight-fixture'].wt-=.01;refreshBattle();});assert(await p.locator('[data-loot-to="fox"]').isEnabled());await p.locator('[data-loot-to="fox"]').tap();assert.equal(await p.evaluate(()=>state.inv.fox.length),capacity.before+1);
 const snapshot=await p.evaluate(()=>JSON.stringify(state.inv));await p.evaluate(()=>refreshBattle());assert.equal(await p.evaluate(()=>JSON.stringify(state.inv)),snapshot);assert(await p.locator('[data-loot]').count()>0);await p.locator('#afterWin').tap();assert.equal(await p.evaluate(()=>state.scene),'caravan');assert.equal(await p.evaluate(()=>JSON.stringify(state.inv)),snapshot);assert.equal(await p.locator('.victory-loot').count(),0);
 await p.evaluate(()=>{state.page='battle';startBattle('worldMimic');B().flowEpoch=(B().flowEpoch||0)+1;B().units.filter(u=>u.side==='foe').forEach(u=>{u.dead=true;u.hp=0;});checkResult();render();});assert.equal(await p.locator('[data-loot]').count(),0);assert.match(await p.locator('.victory-loot').innerText(),/沒有剩餘/);assert(await p.locator('#afterWin').isEnabled());
 assert.deepEqual(errors,[]);console.log('✓ actual 390×844 touch list→four specified backpacks, 3 identical copies, remaining gear+ground, consumed excluded, original focus identity/quality/stat, exact capacity/overweight, duplicate/repaint safe, no auto-equip, leave unwanted+caravan, empty mimic, floor DOM retained, screenshots');
}finally{await browser.close();}
