import assert from 'node:assert/strict';import {chromium} from 'playwright';import path from 'node:path';import fs from 'node:fs/promises';
const out=process.env.CHEST_SHOTS||'/tmp/chest-review';await fs.mkdir(out,{recursive:true});const browser=await chromium.launch();
try{
 const p=await browser.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('https://fonts.googleapis.com/**',r=>r.abort());await p.addInitScript(()=>localStorage.setItem('fuwa-help-seen','{"shop":1,"map":1}'));await p.goto('file://'+path.resolve('index.html')+'#town');await p.waitForFunction(()=>!document.body.classList.contains('image-boot'));
 const data=await p.evaluate(()=>{
  const parse=markup=>{const el=document.createElementNS('http://www.w3.org/2000/svg','svg');el.innerHTML=markup;return el;};
  const cases=Object.entries(CHEST_PALETTES).map(([rarity,palette])=>{const closed=chestSVG({rarity},0,0),open=chestSVG({rarity,opened:true},0,0),el=parse(closed);return {rarity,name:palette.name,closed,open,wood:[...el.querySelectorAll('.chest-wood[fill]:not([fill="none"])')].map(n=>n.getAttribute('fill')),metal:el.querySelector('.chest-lock').getAttribute('fill'),expected:palette.metal,sparkles:el.querySelectorAll('.chest-sparkle').length,expectedSparkles:palette.sparkles,opened:parse(open).querySelector('.chest-lid').getAttribute('transform')};});
  return {cases,default:parse(chestSVG()).querySelector('[data-chest-rarity]').dataset.chestRarity,fallback:parse(chestSVG({rarity:'unknown'})).querySelector('[data-chest-rarity]').dataset.chestRarity,count:gameImageSources().length};
 });
 assert.equal(data.cases.length,5);assert.equal(new Set(data.cases.map(c=>c.metal)).size,5);assert.equal(data.default,'common');assert.equal(data.fallback,'common');assert.equal(data.count,76);
 for(const c of data.cases){assert.deepEqual(c.wood,data.cases[0].wood);assert.equal(c.metal,c.expected);assert.equal(c.sparkles,c.expectedSparkles);assert.match(c.opened,/translate\(-7 -36\)/);}
 const gallery=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:2});await gallery.setContent(`<html lang="zh-Hant"><meta charset="utf-8"><style>*{box-sizing:border-box}body{margin:0;padding:14px;background:#1f1a24;color:#fff1d9;font-family:'Noto Sans CJK TC',sans-serif}h1{font-size:20px;margin:0 0 10px}main{display:grid;grid-template-columns:1fr 1fr;gap:10px}.card{background:#e5d3ae;border:3px solid #403023;border-radius:14px;text-align:center;color:#403023;padding:6px}.card svg{display:block;width:100%;height:164px}.card b{font-size:16px}.note{font-size:12px;color:#c6b6c0;margin-top:10px}</style><h1>寶箱色調・暫定</h1><main>${data.cases.map(c=>`<div class="card"><b>${c.name}</b><svg viewBox="-80 -90 160 145">${c.closed}</svg></div>`).join('')}<div class="card"><b>打開（沿用原互動）</b><svg viewBox="-90 -120 180 185">${data.cases[0].open}</svg></div></main><p class="note">木頭同色，金屬色調與亮點區分稀有度。</p></html>`);await gallery.screenshot({path:out+'/rarities.png'});
 await p.evaluate(()=>{state.page='story';state.scene='worldChest';state.line=0;render();});await p.waitForTimeout(550);assert.equal(await p.locator('.story-chest [data-chest-rarity="common"]').count(),1);await p.screenshot({path:out+'/story.png'});
 await p.evaluate(()=>{window.setTimeout=()=>0;window.setInterval=()=>0;quickBattle();B().tut=-1;B().busy=false;render();});
 const shared=await p.evaluate(()=>Object.keys(CHEST_PALETTES).every(rarity=>{const o={kind:'chest',x:2,y:3,rarity,opened:true};const p=iso(o.x,o.y);return blockSVG(o)===chestSVG(o,p.x,p.y+TH/2);}));assert(shared,'exploration and story use the same chest renderer');assert.deepEqual(errors,[]);console.log('✓ 5 rarity palettes, unchanged wood, lock/metal colors, 0/0/1/2/3 glints, default/invalid fallback, open state, story and exploration shared renderer, boot remains 76 images, 390×844 screenshots');
}finally{await browser.close();}
