import {chromium} from 'playwright';import assert from 'node:assert/strict';import path from 'node:path';
import {bootReady} from './boot.mjs';
const br=await chromium.launch();try{const pg=await br.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const errors=[];pg.on('pageerror',e=>errors.push(e.message));await pg.goto('file://'+path.resolve('index.html')+'#battle?seed=123');await bootReady(pg);
const r=await pg.evaluate(()=>{const b=B(),u=b.units.find(v=>v.id==='fox'),e=b.units.find(v=>v.side==='foe');b.flowEpoch=(b.flowEpoch||0)+1;b.def.blocks=[];b.def.elev=[];delete b.def._h;b.info=null;b.exploreStopped=false;b.exploreStopReason=null;for(const p of b.units.filter(v=>v.side==='pc')){p.x=20;p.y=20;p.statuses=[];p.mods.WIS=0;p.hp=p.maxHp=30;}u.x=12;u.y=12;for(const f of b.units.filter(v=>v.side==='foe')){f.x=1;f.y=1;f.squad=9;f.statuses=[];}e.x=9;e.y=12;e.squad=7;e.type='goblin';e.weapon=ITEMS.find(i=>i.n==='彎刀');e.focus=null;e.innate=[];e.trapCharges=1;Math.random=()=>.99;enterExploreCombat(e.id,true);b.flowEpoch=(b.flowEpoch||0)+1;b.turn=b.units.indexOf(e);beginTurn(e);b.busy=false;aiTurn(e);b.flowEpoch=(b.flowEpoch||0)+1;const trap=b.def.blocks.find(o=>o.owner===e.id),out={random:generateRandomBattle(123).foes.every(f=>f.trapCharges===1),fixed:BATTLES.ambush.foes.every(f=>!f.trapCharges),placed:!!trap,used:b.actionUsed,charge:e.trapCharges,adj:dist(e,trap),hidden:!trap.found};out.noMore=!placeEnemyTrap(e,{x:e.x,y:e.y-1});
// 戰棋移動踩中：保留傷害、停在陷阱，不走完原路，不允許取消。
e.x=1;e.y=1;b.turn=b.units.indexOf(u);beginTurn(u);b.busy=false;b.menu='root';u.x=11;u.y=12;u.statuses=[];u.hp=30;b.moveLeft=6;Math.random=()=>0;pcMove(9,12);out.stop={x:u.x,y:u.y,hp:u.hp,rolled:b.moveRolled,pending:!!b.pendingMove,left:b.moveLeft,once:trap.triggered};const hp=u.hp;exploreTraps(u);out.noDouble=u.hp===hp;
// 快照重試還原開戰時未用的份數，不複製已放的陷阱。
b.result='lose';retryBattle();const fresh=B();fresh.flowEpoch=(fresh.flowEpoch||0)+1;out.retry=fresh.units.find(v=>v.id===e.id).trapCharges===1&&!fresh.def.blocks.some(o=>o.owner===e.id);
// 實際探索點陷阱與拆除，同一個既有互動選單。
fresh.units.filter(v=>v.side==='foe').forEach(v=>v.dead=true);beginExplore();const p=exploreUnit();p.x=12;p.y=12;p.mods.WIS=3;p.mods.DEX=3;fresh.def.blocks=[{kind:'trap',x:12,y:13,owner:e.id}];fresh.def.elev=[];delete fresh.def._h;exploreTraps();out.found=fresh.def.blocks[0].found;fresh.panel=null;fresh.info=null;Math.random=()=>.99;refreshBattle();centerCam(13,12);return out;});
assert(r.random&&r.fixed&&r.placed&&r.used&&r.hidden&&r.noMore);assert.equal(r.charge,0);assert.equal(r.adj,1);assert.deepEqual(r.stop,{x:10,y:12,hp:29,rolled:true,pending:false,left:5,once:true});assert(r.noDouble&&r.retry&&r.found);
await pg.waitForTimeout(400);const bb=await pg.locator('.explore-trap').boundingBox();assert(bb);await pg.touchscreen.tap(bb.x+bb.width/2,bb.y+bb.height/2);await pg.waitForFunction(()=>!!B().exploreObject);await pg.locator('[data-explore-cmd="disarm"]').tap();assert(await pg.evaluate(()=>B().def.blocks[0].disarmed));await pg.waitForTimeout(400);if(process.env.REVIEW_SHOT)await pg.screenshot({path:process.env.REVIEW_SHOT});assert.deepEqual(errors,[]);console.log('✓ AI 真正放置、動作與一份上限、固定伏擊不變、戰棋觸發停止及退款、一次傷害、重試還原、手機發現拆除');}finally{await br.close();}
