import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
const sword={id:'sword',type:'weapon',props:[],n:'劍'},bow={id:'bow',type:'weapon',props:['雙手'],n:'弓'},focus={id:'focus',type:'focus',props:[],n:'法器'},shield={id:'shield',type:'shield'},armor={id:'armor',type:'armor'},bag={id:'bag',type:'gear',bag:1},extra={id:'new',type:'armor'};
const all=[sword,bow,focus,shield,armor,bag,extra];
const state={inv:{fox:all.slice(0,6).map(i=>i.id)},startingGear:{},page:'story',battle:null,townRest:null};
const ctx={state,invItems:id=>(state.inv[id]||[]).map(id=>all.find(i=>i.id===id)),equipmentRequirement:()=>false,abilityScore:()=>16,bestBag:pool=>pool.find(i=>i.bag)||null,isTwoHand:it=>!!it?.props?.includes('雙手'),weaponProps:it=>it.props||[],isBag:it=>!!it.bag,B:()=>state.battle,blog:()=>{}};
ctx.progressionUnits=id=>[state.battle,state.townRest].flatMap(b=>(b?.units||[]).filter(u=>u.id===id));
vm.createContext(ctx);vm.runInContext(fs.readFileSync('js/equipment.js','utf8'),ctx);const eq=vm.runInContext('Equipment',ctx);
ctx.syncBattleBag=u=>{u.items=(u.backpack||[]).filter(i=>i.type==='consumable');eq.save(u);};
let u={id:'fox',side:'pc',hp:7,...eq.read('fox')};u.focus=focus;u.backpack=u.backpack.filter(i=>i!==focus);eq.save(u);
let restored=eq.read('fox');assert.equal(restored.weapon.id,'sword');assert.equal(restored.focus.id,'focus');assert(!restored.backpack.includes(focus));
state.townRest={units:[u]};state.inv.fox.push(extra.id);eq.refresh('fox');assert(u.backpack.includes(extra));assert.equal(u.hp,7);
state.inv.fox.splice(state.inv.fox.indexOf(armor.id),1);eq.refresh('fox');assert.equal(u.armor,null);assert(!u.backpack.includes(armor));
u.focus=null;u.backpack.push(focus);eq.save(u);state.battle=state.townRest;state.townRest=null;state.page='battle';state.battle.freeUsed=1;state.battle.actionUsed=true;
assert(eq.switchUnit(u,2));assert.equal(u.weapon.id,'bow');assert.equal(u.shield,false);assert.equal(u.offhand2.type,'shield');assert.equal(state.battle.freeUsed,1);assert.equal(state.battle.actionUsed,true);
assert(eq.takeHeld(u,bow));assert(!state.inv.fox.includes(bow.id));assert.equal(eq.read('fox').weapon,null);
assert(eq.equipHeld(u,bow));assert(state.inv.fox.includes(bow.id));assert.equal(eq.read('fox').weapon.id,'bow');
assert(eq.move(u,'weapon1','bag'));assert.equal(eq.read('fox').weapon,null);assert(eq.read('fox').backpack.includes(bow));
state.battle=null;state.page='story';eq.set('fox',{main:'sword',second:'bow',focus:'focus',off:'shield',armor:null,bag:'bag',accessories:[]});restored=eq.read('fox');assert.equal(restored.focus.id,'focus');
delete state.startingGear.fox;state.inv.fox=['sword','sword','sword','bag'];restored=eq.read('fox');assert.equal(restored.backpack.filter(i=>i.id==='sword').length,1,'同類物品逐件分配，沒有吞掉第三件');
for(const file of ['js/main.js','js/magic-shop.js','js/sealed-goods.js'])assert(fs.readFileSync(file,'utf8').includes('Equipment.refresh('));
assert(!fs.readFileSync('js/ui/status-card.js','utf8').includes('const shieldId='));
console.log('PASS：裝備唯一入口；武器＋法器保存、購退同步、切組與資源保留、繳械拾取、換裝及重複物品分配。');
