import {chromium} from 'playwright';import assert from 'node:assert/strict';import path from 'node:path';import {fileURLToPath} from 'node:url';
const br=await chromium.launch(),pg=await br.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),errors=[];pg.on('pageerror',e=>errors.push(e.message));const shot=async n=>{if(process.env.COMBAT_SHOTS)await pg.screenshot({path:process.env.COMBAT_SHOTS+'/'+n+'.png'});};
try{
 await pg.goto('file://'+path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../index.html')+'#battle?seed=123');await pg.waitForFunction(()=>typeof B==='function'&&B()&&!document.body.classList.contains('image-boot'));await pg.waitForTimeout(500);
 await pg.evaluate(()=>{const b=B();b.def.blocks=[];b.def.elev=[];delete b.def._h;exploreParty().forEach((p,i)=>{p.x=15;p.y=17+i;p.statuses=[];p.mods.DEX=4;});b.units.filter(u=>u.side==='foe').forEach((e,i)=>{e.x=i<2?10+i:1;e.y=i<2?17:2+i;e.type='goblin';e.squad=Math.floor(i/2);e.statuses=[];e.mods.WIS=0;e.mods.DEX=-4;});const far=b.units.find(u=>u.id==='raccoon');far.x=21;far.y=25;b.info=null;b.exploreStopped=false;Math.random=()=>.99;refreshBattle();centerCam(14,17);window.__layers=['board-floor','board-marks','board-scene'].map(id=>document.getElementById(id));});
 await shot('explore');await pg.evaluate(()=>exploreDetect());assert.equal(await pg.evaluate(()=>B().phase),'combat');assert(await pg.evaluate(()=>{const pcs=B().units.filter(u=>u.side==='pc'&&!u.dead&&!u.fled),lead=B().units.find(u=>u.id==='fox');return new Set(pcs.map(u=>`${u.x},${u.y}`)).size===pcs.length&&pcs.every(u=>Math.hypot(u.x-lead.x,u.y-lead.y)<1.5);}), '切戰棋後四隻在目前探索位置就近唯一佈署');assert.equal(await pg.evaluate(()=>B().units.filter(u=>u.side==='foe'&&u.combatActive).length),2);await shot('combat');
 assert(await pg.evaluate(()=>window.__layers.every((e,i)=>e===document.getElementById(['board-floor','board-marks','board-scene'][i]))));
 assert(await pg.evaluate(()=>B().units.filter(u=>u.side==='foe'&&u.combatActive).every(u=>!u.surprised)),'敵人看到沒潛行玩家，不奇襲');assert(await pg.evaluate(()=>B().units.find(u=>u.id==='raccoon').surprised),'個別遠方角色沒察覺');
 const init=await pg.evaluate(()=>B().units.filter(u=>u.combatActive).map(u=>[u.id,u.init]));await pg.evaluate(()=>{const b=B(),e=b.units.find(u=>u.side==='foe'&&!u.combatActive);e.x=9;e.y=20;b.turn=b.units.length-1;b.round=1;nextTurn();});assert.equal(await pg.evaluate(()=>B().units.filter(u=>u.side==='foe'&&u.combatActive).length),4,'聽到8格內打鬥，整隊加入');assert.deepEqual(await pg.evaluate(old=>old.map(([id])=>{const u=B().units.find(u=>u.id===id);return [id,u.init];}),init),init,'原先攻不重擲');await shot('reinforcements');
 // retry snapshots the fight, including HP, positions and terrain, without recreating the map.
 const snap=await pg.evaluate(()=>JSON.parse(JSON.stringify(state.battleSnap.battle)));await pg.evaluate(()=>{B().units.find(u=>u.id==='fox').hp=1;B().def.blocks.push({x:20,y:20,kind:'crate'});B().result='lose';retryBattle();});assert.equal(await pg.evaluate(()=>B().units.find(u=>u.id==='fox').hp),snap.units.find(u=>u.id==='fox').hp);assert.equal(await pg.evaluate(()=>B().def.blocks.length),snap.def.blocks.length);assert.equal(await pg.evaluate(()=>B().units.filter(u=>u.side==='foe'&&u.combatActive).length),2);await shot('retry');
 await pg.evaluate(()=>{B().units.filter(u=>u.side==='foe'&&u.combatActive).forEach(u=>{u.dead=true;u.hp=0;});checkResult();});assert.equal(await pg.evaluate(()=>B().phase),'explore');assert.equal(await pg.locator('.bt-victory').count(),0);await shot('return-explore');
 await pg.evaluate(()=>{exploreParty().forEach(u=>{u.slots=slotMax(u).map(()=>0);});state.shortRestsUsed=0;refreshBattle();});await pg.locator('[data-explore-cmd="rest"]').click();await shot('rest');await pg.locator('#shortRest').click();assert.equal(await pg.evaluate(()=>state.shortRestsUsed),1);assert(await pg.evaluate(()=>exploreParty().every(u=>slotsOf(u).every((s,i)=>s===Math.ceil(slotMax(u)[i]/2)))));await pg.locator('#shortRest').click();assert.equal(await pg.evaluate(()=>state.shortRestsUsed),2);assert(await pg.locator('#shortRest').isDisabled());await pg.locator('#longRest').click();assert.equal(await pg.evaluate(()=>state.shortRestsUsed),0);assert(await pg.evaluate(()=>exploreParty().every(u=>slotsOf(u).every((s,i)=>s===slotMax(u)[i]))));await pg.locator('[data-camp-who="wolf"]').click();assert.equal(await pg.evaluate(()=>state.scene),'camp');await pg.evaluate(()=>finishCamp());await shot('rest-complete');await pg.locator('[data-explore-cmd="rest"]').click();
 // Genuine manual button: hidden party gives enemy individual surprise and prohibits reactions until its turn ends.
 await pg.evaluate(()=>{const b=B();exploreParty().forEach((p,i)=>{p.x=15;p.y=17+i;p.statuses=[{k:'hidden',val:30,roll:20}];});const e=b.units.find(u=>u.side==='foe'&&!u.dead);e.x=11;e.y=17;e.squad=9;b.info=e.id;b.exploreStopped=false;refreshBattle();});await pg.locator('[data-explore-cmd="combat"]').click();assert.equal(await pg.evaluate(()=>B().phase),'combat');assert.equal(await pg.evaluate(()=>B().units.filter(u=>u.side==='foe'&&u.combatActive).length),0,'切模式不開戰');await pg.evaluate(()=>{const b=B(),e=b.units.find(u=>u.id===b.info)||b.units.find(u=>u.side==='foe'&&!u.dead&&!u.fled);engageExploreSquad(e,cur());});assert(await pg.evaluate(()=>B().units.filter(u=>u.side==='foe'&&u.combatActive).every(u=>u.surprised)));assert(await pg.evaluate(()=>B().units.filter(u=>u.side==='foe'&&u.combatActive).every(u=>!canOA(u))));await shot('surprise');
 await pg.evaluate(()=>{const b=B(),e=b.units.find(u=>u.side==='foe'&&u.combatActive);b.turn=b.units.indexOf(e)-1;nextTurn();});assert.equal(await pg.evaluate(()=>B().moveLeft),0);assert(await pg.evaluate(()=>B().actionUsed&&B().freeUsed));await pg.waitForTimeout(1200);assert(await pg.evaluate(()=>B().units.filter(u=>u.side==='foe'&&u.combatActive).every(u=>!u.surprised)));
 await pg.evaluate(()=>{B().units.filter(u=>u.side==='foe'&&u.combatActive).forEach(u=>u.fled=true);checkResult();});assert.equal(await pg.evaluate(()=>B().phase),'explore','敵人離場可回探索');
 await pg.evaluate(()=>{B().units.filter(u=>u.side==='foe').forEach(u=>u.dead=true);B().info=null;refreshBattle();});await pg.locator('[data-explore-cmd="combat"]').click();assert(await pg.evaluate(()=>B().manualCombat));await pg.locator('[data-explore-cmd="return"]').click();assert.equal(await pg.evaluate(()=>B().phase),'explore');
 // 10-09 昏迷規則：三隻昏迷、敵人清光→回探索、昏迷的醒來 1 血；四隻都昏迷＝輸
 await pg.evaluate(()=>{enterExploreCombat(null,true);const b=B();b.manualCombat=false;b.units.filter(u=>u.side==='pc'&&u.id!=='fox').forEach(u=>{u.down=true;u.hp=0;});checkResult();});assert.equal(await pg.evaluate(()=>B().phase),'explore');assert(await pg.evaluate(()=>B().units.filter(u=>u.side==='pc').every(u=>!u.down&&u.hp>=1)),'戰後昏迷的醒來');
 await pg.evaluate(()=>{enterExploreCombat(null,true);const b=B();b.manualCombat=false;b.units.filter(u=>u.side==='pc').forEach(u=>{u.down=true;u.hp=0;});});assert.equal(await pg.evaluate(()=>checkResult()),true);assert.equal(await pg.evaluate(()=>B().result),'lose','四隻都昏迷＝輸');
 await pg.evaluate(()=>{const b=B();b.result=null;b.phase='explore';b.exploreStopped=false;b.exploreStopReason=null;b.units.filter(u=>u.side==='pc').forEach(u=>{u.dead=false;u.down=false;u.hp=20;});exploreParty().forEach((p,i)=>{p.x=15;p.y=17+i;p.mods.WIS=0;p.statuses=[];});const e=b.units.find(u=>u.side==='foe');e.fled=false;e.dead=false;e.down=false;e.x=13;e.y=17;e.squad=20;e.type='goblin';e.statuses=[{k:'hidden',val:30,roll:20}];b.def.blocks=[{x:e.x,y:e.y,kind:'bush'}];exploreDetect();});assert.equal(await pg.evaluate(()=>B().phase),'combat');assert(await pg.evaluate(()=>B().units.filter(u=>u.side==='pc').every(u=>u.surprised)),'敵方潛行先察覺我方：保留現身前的個別奇襲判定');
 await pg.evaluate(()=>{const b=B();b.phase='explore';b.flowEpoch++;b.units.filter(u=>u.side==='foe').forEach(u=>u.dead=true);exploreParty().forEach(u=>u.statuses=[]);b.leader='fox';b.exploreSolo='fox';b.turn=b.units.findIndex(u=>u.id==='fox');b.busy=false;b.exploreStopped=false;b.exploreStopReason=null;const p=exploreUnit();p.hp=1;b.def.blocks=[{x:p.x,y:p.y,kind:'trap'}];exploreTraps(p);refreshBattle();});assert(await pg.evaluate(()=>B().units.find(u=>u.id==='fox').down));await pg.locator('[data-explore-cmd="resume"]').click();assert.notEqual(await pg.evaluate(()=>B().leader),'fox','隊長倒下由清醒同伴接手');assert(await pg.evaluate(()=>!exploreUnit().down));
 assert.deepEqual(errors,[]);console.log('✓ 探索原地切戰棋、2隻小隊、8格增援及先攻保存、個別奇襲與反應、開戰快照重試、回探索、手機休息及每日次數');
}finally{await br.close();}
