import {chromium} from 'playwright';import assert from 'node:assert/strict';import path from 'node:path';import {fileURLToPath} from 'node:url';
const br=await chromium.launch(),pg=await br.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),errors=[];pg.on('pageerror',e=>errors.push(e.message));
const shot=async n=>{if(process.env.OBJECT_SHOTS)await pg.screenshot({path:process.env.OBJECT_SHOTS+'/'+n+'.png'});};
const tap=async(x,y)=>{const p=await pg.evaluate(({x,y})=>{centerCam(x,y);const r=document.querySelector('.board-wrap').getBoundingClientRect(),p=iso(x,y),z=camZoom();return {x:r.left+B().cam.x+p.x*z,y:r.top+B().cam.y+(p.y+TH/2)*z};},{x,y});await pg.touchscreen.tap(p.x,p.y);};
try{
 await pg.goto('file://'+path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../index.html')+'#battle?seed=123');
 await pg.evaluate(()=>{const b=B();b.def.blocks=[];b.def.elev=[];delete b.def._h;b.units.filter(u=>u.side==='foe').forEach((u,i)=>{u.x=1;u.y=i+1;u.statuses=[];});exploreParty().forEach((p,i)=>{p.x=15;p.y=17+i;p.mods.WIS=-4;p.statuses=[];});b.leader='fox';b.turn=b.units.findIndex(u=>u.id==='fox');b.exploreStopped=false;b.def.blocks=[{x:17,y:17,kind:'chest',locked:true,contents:[]},{x:18,y:19,kind:'door'},{x:16,y:21,kind:'crate'},{x:18,y:22,kind:'trap'}];refreshBattle();window.__floor=document.getElementById('board-floor').firstElementChild;window.__scene=document.getElementById('board-scene');});
 await tap(17,17);try{await pg.waitForFunction(()=>!!B().exploreObject);}catch(e){console.log(await pg.evaluate(()=>({o:B().exploreObject,goal:B().exploreGoal,busy:B().busy,stop:B().exploreStopped,log:B().log,pcs:exploreParty().map(p=>[p.id,p.x,p.y])})));throw e;}assert(await pg.evaluate(()=>dist(exploreUnit(),B().exploreObject)<=1),'點寶箱後走到旁邊');await shot('chest-menu');
 await pg.evaluate(()=>{Math.random=()=>0;});await pg.locator('[data-explore-cmd="unlock"]').click();assert.equal(await pg.evaluate(()=>B().exploreObject.opened),undefined,'失敗保持鎖住');
 await pg.evaluate(()=>{Math.random=()=>.99;});await pg.locator('[data-explore-cmd="pry"]').click();assert.equal(await pg.evaluate(()=>B().exploreObject.opened),undefined,'沒有鐵撬不能撬');
 await pg.locator('[data-explore-cmd="unlock"]').click();assert(await pg.evaluate(()=>B().exploreObject.opened));await pg.locator('[data-explore-cmd="search"]').click();await shot('chest-open');
 await pg.evaluate(()=>{const o=B().exploreObject;o.opened=false;o.locked=true;exploreUnit().backpack.push({n:'測試套組',contains:['鐵撬']});});await pg.locator('[data-explore-cmd="pry"]').click();assert(await pg.evaluate(()=>B().exploreObject.opened),'套組鐵撬可撬');await pg.locator('[data-explore-cmd="close"]').click();
 await pg.evaluate(()=>{const p=exploreUnit();p.x=17;p.y=19;refreshBattle();});await tap(18,19);assert(await pg.evaluate(()=>blocked(18,19)));assert.equal(await pg.evaluate(()=>coverOf({x:17,y:19,side:'pc'},{x:19,y:19,side:'foe'}).v),.75);await pg.locator('[data-explore-cmd="door"]').click();assert.equal(await pg.evaluate(()=>blocked(18,19)),false);assert.equal(await pg.evaluate(()=>coverOf({x:17,y:19,side:'pc'},{x:19,y:19,side:'foe'}).v),0);await shot('door-open');
 await pg.evaluate(()=>{const p=exploreParty().find(p=>p.id!=='fox');p.x=18;p.y=19;});await pg.locator('[data-explore-cmd="door"]').click();assert.equal(await pg.evaluate(()=>blocked(18,19)),false,'不能關在角色身上');await pg.evaluate(()=>{const p=exploreParty().find(p=>p.id!=='fox');p.x=20;p.y=20;});await pg.locator('[data-explore-cmd="door"]').click();assert(await pg.evaluate(()=>blocked(18,19)));await shot('door-closed');await pg.locator('[data-explore-cmd="close"]').click();
 await pg.evaluate(()=>{exploreUnit().x=15;exploreUnit().y=21;refreshBattle();});await tap(16,21);await pg.locator('[data-explore-cmd="push"]').click();assert(await pg.evaluate(()=>blocked(17,21)));assert.equal(await pg.evaluate(()=>blocked(16,21)),false);await shot('crate-push');
 await pg.evaluate(()=>{const p=exploreUnit();p.x=17;p.y=22;p.mods.WIS=3;exploreTraps();refreshBattle();});assert(await pg.evaluate(()=>B().def.blocks.find(o=>o.kind==='trap').found));await tap(18,22);await shot('trap-found');await pg.locator('[data-explore-cmd="disarm"]').click();assert(await pg.evaluate(()=>B().def.blocks.find(o=>o.kind==='trap').disarmed));await shot('trap-disarmed');
 await pg.evaluate(()=>{const b=B(),p=exploreUnit();p.x=17;p.y=22;p.hp=p.maxHp=20;p.mods.WIS=-4;exploreParty().forEach(p=>p.mods.WIS=-4);b.exploreSolo='fox';b.def.blocks=b.def.blocks.filter(o=>o.kind!=='trap');b.def.blocks.push({x:18,y:22,kind:'trap'});b.exploreObject=null;refreshBattle();});
 assert.equal(await pg.evaluate(()=>blockSVG(B().def.blocks.find(o=>o.kind==='trap'))),'','未發現不畫陷阱');await tap(18,22);try{await pg.waitForFunction(()=>B().exploreStopReason==='trap');}catch(e){console.log(await pg.evaluate(()=>({pcs:exploreParty().map(p=>[p.id,p.x,p.y]),stop:B().exploreStopped,reason:B().exploreStopReason,goal:B().exploreGoal,log:B().log.slice(-5),blocks:B().def.blocks})));throw e;}assert.equal(await pg.evaluate(()=>exploreUnit().hp),14,'1d6 使用原傷害流程');assert(await pg.locator('.bt-hud').innerText().then(t=>t.includes('踩中陷阱')));await shot('trap-trigger');await pg.locator('[data-explore-cmd="resume"]').click();assert.equal(await pg.evaluate(()=>B().exploreStopped),false);await tap(19,22);try{await pg.waitForFunction(()=>!B().busy);}catch(e){console.log(await pg.evaluate(()=>({busy:B().busy,moveId:B().exploreMoveId,goal:B().exploreGoal,pcs:exploreParty().map(p=>[p.id,p.x,p.y]),log:B().log.slice(-5)})));throw e;}assert.equal(await pg.evaluate(()=>exploreUnit().hp),14,'陷阱不重複觸發');
 assert(await pg.evaluate(()=>document.getElementById('board-floor').firstElementChild===window.__floor));assert(await pg.evaluate(()=>document.getElementById('board-scene')===window.__scene));assert.deepEqual(errors,[]);console.log('✓ 觸控點物件後隊長靠近、寶箱檢定及鐵撬套組、門擋路擋視線、防關門占位、推箱改占位、陷阱發現拆除傷害停下續行、原圖層保留');
}finally{await br.close();}
