import {chromium} from 'playwright';import assert from 'node:assert/strict';import path from 'node:path';
import {bootReady,noLuck} from './boot.mjs';
const br=await chromium.launch(),pg=await br.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),errs=[];pg.on('pageerror',e=>errs.push(e.message));
try{
 await pg.goto('file://'+path.resolve('index.html')+'#battle');await bootReady(pg);await noLuck(pg);await pg.waitForTimeout(300);
 await pg.evaluate(()=>{state.modal=null;startBattle('ambush',false,'explore');const b=B(),u=b.units.find(v=>v.id==='raccoon'),t=b.units.find(v=>v.side==='foe');b.phase='combat';b.explorationMap=false;b.flowEpoch++;b.turn=b.units.indexOf(u);b.def.blocks=[];b.tut=-1;u.weapon=ITEMS.find(i=>i.n==='長劍');u.offhand=ITEMS.find(i=>i.n==='匕首');u.shield=false;u.focus=null;u.mods.STR=1;u.mods.DEX=4;u.statuses=[];t.x=u.x+1;t.y=u.y;t.hp=t.maxHp=200;t.dead=t.down=false;beginTurn(u);b.busy=false;b.menu='act';centerCam(u.x,u.y,true);refreshBattle();});
 assert.equal(await pg.locator('[data-skill="offhand_attack"]').count(),1);assert(await pg.locator('.eco').allTextContents().then(a=>a.includes('免費 2/2')));
 await pg.waitForTimeout(400);await pg.screenshot({path:'/tmp/free-offhand-options.png'});
 await pg.locator('[data-skill="offhand_attack"]').tap();assert.equal(await pg.evaluate(()=>B().mode.key),'offhand_attack');
 const off=await pg.evaluate(()=>{const b=B(),u=cur(),t=b.units.find(v=>v.side==='foe'),sk=unitSkills(u).find(s=>s.key==='offhand_attack');const roll=attackRoll,h= hurt,rnd=Math.random;let bonus,n,type;attackRoll=(a,t,o)=>(bonus=o.bonus,{hit:true,crit:false});hurt=(t,d,k)=>{n=d;type=k;};Math.random=()=>.5;doSkill(u,sk,t);const first={free:freeRemaining(),action:b.actionUsed,used:u.offhandAttackUsed,bonus,n,type,main:u.weapon.n,off:u.offhand.n};doSkill(u,sk,t);u.spare=[ITEMS.find(i=>i.n==='短弓')];switchWeaponSet(u,2);const kept=u.offhandAttackUsed;attackRoll=roll;hurt=h;Math.random=rnd;return {first,kept,free:freeRemaining()};});
 assert.deepEqual(off.first,{free:1,action:false,used:true,bonus:6,n:7,type:'穿刺',main:'長劍',off:'匕首'});assert(off.kept);assert.equal(off.free,1);
 await pg.waitForTimeout(2400);
 const checks=await pg.evaluate(()=>{const b=B(),u=cur(),t=b.units.find(v=>v.side==='foe');beginTurn(u);b.busy=false;u.weapon=makeItem(ITEMS.find(i=>i.n==='霜雷法杖'),false);u.offhand=null;u.shield=false;u.focus=null;u.activeSkills=[];u.statuses=[];u.spare=[];const ray=unitSkills(u).find(s=>s.key==='ray_of_frost'),shock=unitSkills(u).find(s=>s.key==='shocking_grasp');const mainAction=[ray,shock].every(s=>!s.def.free&&!s.def.turnLimit);u.silenced=true;doSkill(u,ray,t);const voice=freeRemaining()===2&&!b.actionUsed;u.silenced=false;doSkill(u,ray,t);const first={free:freeRemaining(),action:b.actionUsed};const blocked=!skillCanUse(u,shock);beginTurn(u);b.busy=false;const reset=!b.actionUsed&&freeRemaining()===2;b.menu='act';refreshBattle();return {mainAction,voice,first,blocked,reset};});   // 10-11 大爺：法器戲法花主要動作
 assert.deepEqual(checks.first,{free:2,action:true});for(const [k,v] of Object.entries(checks))if(k!=='first')assert(v,k);
 await pg.waitForTimeout(400);await pg.screenshot({path:'/tmp/free-cantrip-options.png'});
 const pair=await pg.evaluate(()=>{const b=B(),u=cur(),t=b.units.find(v=>v.side==='foe');u.weapon=makeItem(ITEMS.find(i=>i.n==='奧術法杖'),false);u.offhand=ITEMS.find(i=>i.n==='匕首');beginTurn(u);b.busy=false;doSkill(u,unitSkills(u).find(s=>s.key==='offhand_attack'),t);u.offhand=null;doSkill(u,unitSkills(u).find(s=>s.key==='arcane_staff_cantrip'),t);return {free:freeRemaining(),main:b.actionUsed,off:u.offhandAttackUsed};});assert.deepEqual(pair,{free:1,main:true,off:true});
 assert.deepEqual(errs,[]);console.log('✓ 副手獨立攻擊與傷害、兩次免費動作、各類一次、換装不重置、成分阻擋不扣動作、回合恢復、共用預算與手機選項');
}finally{await br.close();}
