import {chromium} from 'playwright';import assert from 'node:assert/strict';import path from 'node:path';
const br=await chromium.launch();try{const pg=await br.newPage({viewport:{width:390,height:844},hasTouch:true});const errors=[];pg.on('pageerror',e=>errors.push(e.message));await pg.goto('file://'+path.resolve('index.html')+'#battle?seed=123');await pg.waitForFunction(()=>typeof B==='function'&&B()&&!document.body.classList.contains('image-boot'));
const r=await pg.evaluate(()=>{const b=B(),u=b.units.find(u=>u.id==='fox');b.flowEpoch=(b.flowEpoch||0)+1;b.def.blocks=[];b.exploreStopped=false;b.exploreSolo='fox';b.exploreGoal=null;b.busy=false;b.tut=-1;b.groundClockAt=null;u.x=10;u.y=10;u.statuses=[];for(const [x,kind] of [[11,'water'],[12,'water'],[13,'water'],[14,'bush'],[15,'bush'],[16,'bush']])b.def.blocks.push({x,y:10,kind});
const out={};groundReact(11,10,'寒冷');groundReact(12,10,'閃電');groundReact(13,10,'火焰');groundReact(14,10,'火焰');out.kinds=[11,12,13,14].map(x=>groundAt(x,10).kind);out.cover=coverOf({x:10,y:10},{x:13,y:10}).v;out.original=groundAt(11,10).left;
b.groundClockAt=1000;b.info={};groundClock(7000);out.paused=groundAt(11,10).left;b.info=null;groundClock(8000);out.elapsed=groundAt(11,10).left;b.phase='combat';groundClock(14000);out.combatNoClock=groundAt(11,10).left;groundAdvance(6000,true);out.round=groundAt(11,10).left;out.steamGone=!groundAt(13,10);out.spreadOne=groundAt(15,10)?.kind==='fire'&&!groundAt(16,10);
u.x=11;const save=saveRoll;saveRoll=()=>false;b.phase='explore';b.exploreIceTried={};out.iceStops=!groundEnter(u,{});out.prone=!!has(u,'prone');out.once=groundEnter(u,{});u.statuses=[];u.x=12;groundReact(12,10,'閃電');out.paralyzed=!!has(u,'paralyzed');groundAdvance(6000);out.persists=!!has(u,'paralyzed');saveRoll=()=>true;groundStatusSave(u);out.released=!has(u,'paralyzed');saveRoll=save;
const foe=b.units.find(u=>u.side==='foe');foe.x=14;foe.y=9;foe.knownGround=[];out.unknown=!groundAvoid(foe,14,10);groundKnown(foe);out.avoid=groundAvoid(foe,14,10);
// 選法術的真實手機操作：空水面可瞄準；使用原戰場與原狀態。
b.phase='combat';b.turn=b.units.indexOf(u);b.manualCombat=true;b.groundEffects={};b.groundPulse=0;b.def.blocks=[{x:11,y:10,kind:'water'}];u.x=10;u.y=10;u.statuses=[];u.weapon=makeItem(ITEMS.find(i=>i.n==='霜雷法杖'));u.focus=null;u.shield=false;u.activeSkills=[];beginTurn(u);b.round=1;b.busy=false;b.actionUsed=b.freeUsed=false;b.result=null;b.menu='act';centerCam(10,10,true);refreshBattle();return out;});
assert.deepEqual(r.kinds,['ice','charged','steam','fire']);assert.equal(r.cover,.5);assert.equal(r.paused,r.original);assert.equal(r.elapsed,r.original-1000);assert.equal(r.combatNoClock,r.elapsed);assert.equal(r.round,r.elapsed-6000);for(const k of ['steamGone','spreadOne','iceStops','prone','once','paralyzed','persists','released','unknown','avoid'])assert(r[k],k);
await pg.locator('[data-skill="ray_of_frost"]').tap();assert.equal(await pg.evaluate(()=>B().mode.key),'ray_of_frost');assert(await pg.evaluate(()=>!!validTarget(cur(),unitSkills(cur()).find(s=>s.key==='ray_of_frost'),11,10)));
await pg.waitForTimeout(400);const tile=await pg.locator('#board-floor polygon.tile[data-tile="11,10"]').boundingBox();assert(tile);const pos={x:tile.x+tile.width/2,y:tile.y+tile.height/2};assert.equal(await pg.evaluate(p=>document.elementFromPoint(p.x,p.y)?.closest("[data-tile]")?.dataset.tile,pos),"11,10");await pg.touchscreen.tap(pos.x,pos.y);await pg.waitForFunction(()=>groundAt(11,10)?.kind==="ice");assert.equal(await pg.evaluate(()=>groundAt(11,10)?.kind),'ice');await pg.waitForTimeout(2200);if(process.env.REVIEW_SHOT)await pg.screenshot({path:process.env.REVIEW_SHOT});assert.deepEqual(errors,[]);console.log('✓ 地面查表、秒／輪計時、暫停、蒸氣遮蔽、逐輪蔓延、冰面停止、麻痺豁免解除、已知危險與手機施法');}finally{await br.close();}
