import {chromium} from 'playwright';import assert from 'node:assert/strict';import path from 'node:path';
const br=await chromium.launch();try{const pg=await br.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const errors=[];pg.on('pageerror',e=>errors.push(e.message));await pg.goto('file://'+path.resolve('index.html')+'#battle?seed=123');
const r=await pg.evaluate(()=>{const b=B(),u=b.units.find(v=>v.id==='fox');b.flowEpoch=(b.flowEpoch||0)+1;b.groundClockAt=null;b.exploreStopped=false;b.exploreSolo=u.id;b.turn=b.units.indexOf(u);b.busy=false;b.def.blocks=[{kind:'poisonSwamp',x:10,y:11}];b.def.elev=[];b.groundEffects={};u.x=10;u.y=11;u.hp=u.maxHp=100;u.statuses=[];u.mods.CON=0;const saved=Math.random;Math.random=()=>0;groundEnter(u);const out={applied:!!has(u,'poisoned'),dc:has(u,'poisoned')?.dc};u.x=10;u.y=10;Math.random=()=>0;for(let i=0;i<4;i++)groundAdvance(6000);out.failed={hp:u.hp,still:!!has(u,'poisoned')};Math.random=()=>.99;groundAdvance(6000);out.success={hp:u.hp,clear:!has(u,'poisoned')};
addStatus(u,'poisoned',{dc:13,n:1});b.phase='combat';beginTurn(u);out.turnDamage=u.hp;out.notCounted=!!has(u,'poisoned');out.noCounter=stTurns(has(u,'poisoned'))===null;out.desc=statusExplain(u,has(u,'poisoned'));Math.random=()=>0;const next=nextTurn;nextTurn=()=>{};endTurn();out.endFail=!!has(u,'poisoned');Math.random=()=>.99;endTurn();out.endSuccess=!has(u,'poisoned');nextTurn=next;Math.random=saved;
b.phase='explore';u.hp=100;u.x=10;u.y=10;u.statuses=[];b.exploreSolo=u.id;b.exploreGoal=null;b.exploreStopped=false;b.exploreIceTried={};b.menu=null;b.info=null;b.panel=null;b.result=null;b.critOn=null;for(const f of b.units.filter(v=>v.side==='foe')){f.x=1;f.y=1;}b.groundPulse=0;b.groundClockAt=Date.now();refreshBattle();centerCam(10,10);return out;});
assert(r.applied);assert.equal(r.dc,13);assert.deepEqual(r.failed,{hp:96,still:true});assert.deepEqual(r.success,{hp:92,clear:true});assert.equal(r.turnDamage,88);assert(r.notCounted);assert(r.noCounter);assert(r.endFail);assert(r.endSuccess);assert.match(r.desc,/體質豁免/);assert.match(r.desc,/DC 13/);
await pg.evaluate(()=>{Math.random=()=>0;});await pg.waitForTimeout(400);const bb=await pg.locator('#board-floor polygon.tile[data-tile="10,11"]').boundingBox();assert(bb);assert.equal(await pg.evaluate(p=>document.elementFromPoint(p.x,p.y)?.closest("[data-tile]")?.dataset.tile,{x:bb.x+bb.width/2,y:bb.y+bb.height/2}),"10,11");await pg.touchscreen.tap(bb.x+bb.width/2,bb.y+bb.height/2);await pg.waitForFunction(()=>!!has(B().units.find(u=>u.id==='fox'),'poisoned'));await pg.waitForFunction(()=>!B().busy);
await pg.evaluate(()=>{const b=B();b.info='fox';b.infoPage='status';refreshBattle();});await pg.waitForTimeout(400);await pg.locator('[data-statustip][aria-label="中毒"]').tap();assert.match(await pg.locator('body').innerText(),/解毒體質豁免 DC 13/);if(process.env.REVIEW_SHOT)await pg.screenshot({path:process.env.REVIEW_SHOT});
const paused=await pg.evaluate(()=>{const b=B(),u=b.units.find(u=>u.id==='fox'),hp=u.hp;b.groundClockAt=1000;groundClock(13000);return u.hp===hp;});assert(paused);assert.deepEqual(errors,[]);console.log('✓ 持續失敗不解毒、成功體質豁免解毒、離開不解毒、回合傷害／結束豁免、探索六秒、毒沼手機移動與狀態卡');}finally{await br.close();}
