import assert from 'node:assert/strict';import {chromium} from 'playwright';import fs from 'node:fs/promises';import path from 'node:path';import http from 'node:http';
const root=process.cwd(),shots=process.env.CHEST_EVENT_SHOTS||'/tmp/chest-event-review';await fs.mkdir(shots,{recursive:true});
const server=http.createServer(async(req,res)=>{try{const f=path.join(root,new URL(req.url,'http://local').pathname);res.setHeader('Content-Type',f.endsWith('.js')?'text/javascript':f.endsWith('.css')?'text/css':f.endsWith('.webp')?'image/webp':'text/html');res.end(await fs.readFile(f));}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch(),errors=[];
const open=async touch=>{const p=await browser.newPage({viewport:{width:390,height:844},hasTouch:touch,isMobile:touch});p.on('pageerror',e=>errors.push(e.message));await p.route('https://fonts.googleapis.com/**',r=>r.abort());await p.addInitScript(()=>localStorage.setItem('fuwa-help-seen','{"map":1,"shop":1}'));await p.goto(`http://127.0.0.1:${server.address().port}/index.html#town`);await p.waitForFunction(()=>!document.body.classList.contains('image-boot'));await p.waitForFunction(()=>!document.getElementById('bootBackdrop')||getComputedStyle(document.getElementById('bootBackdrop')).opacity==='0');return p;};
async function advance(p){const before=await p.evaluate(()=>state.line);await p.locator('#stage').click();await p.waitForFunction(n=>state.line===n+1,before);}
async function setup(p,{tier=0,mimic=false,gold=7}={}){await p.evaluate(({tier,mimic,gold})=>{state.modal=null;state.travel={route:['town','forest'],from:'town',to:'forest',leg:0,t:.56,elapsed:3.7,banterAt:100,chest:true,chestSeen:true,alert:true,paused:false,running:false};state.location='town';state.worldArrival=null;const [rarity,dc]=WORLD_CHEST_TIERS[tier];state.worldChest={rarity,dc,gold,mimic,status:'locked',attempts:[],paid:false};state.page='story';state.scene='worldChest';state.line=5;render();},{tier,mimic,gold});}
try{
 const p=await open(false),downloads=[];p.on('request',r=>{if(/\.webp/.test(r.url()))downloads.push(r.url());});
 // User's blue overlay: stage images cannot be selected or natively dragged.
 await p.evaluate(()=>{state.page='story';state.scene='ambush';state.line=0;render();});await p.locator('#stage').focus();await p.keyboard.press('Control+a');assert.equal(await p.locator('#stage').evaluate(e=>getComputedStyle(e).userSelect),'none');assert.equal(await p.locator('.scene-bg img').evaluate(e=>e.draggable),false);assert.equal(await p.evaluate(()=>window.getSelection().containsNode(document.querySelector('.scene-bg img'),true)),false);
 await p.evaluate(()=>{window.__nativeDrags=0;document.addEventListener('dragstart',()=>window.__nativeDrags++);});const bg=await p.locator('.scene-bg img').boundingBox();await p.mouse.move(bg.x+70,bg.y+90);await p.mouse.down();await p.mouse.move(bg.x+170,bg.y+160,{steps:8});await p.mouse.up();assert.equal(await p.evaluate(()=>window.__nativeDrags),0);await p.evaluate(()=>{state.line=0;updateStoryLine();});
await p.evaluate(()=>{window.getSelection().removeAllRanges();document.activeElement.blur();});await p.waitForTimeout(550);await p.screenshot({path:shots+'/goblins.png'});
 await p.evaluate(()=>{window.getSelection().removeAllRanges();state.scene='townSupplier';state.line=0;render();});assert.equal(await p.locator('.scene-bg img').getAttribute('data-image-source')||await p.locator('.scene-bg img').getAttribute('src'),'assets/scenes/town.webp');await p.waitForTimeout(1100);await p.screenshot({path:shots+'/supplier.png'});
 // Default zoom leaves real vertical and horizontal drag range.
 await p.evaluate(()=>{state.page='map';state.travel=null;state.worldArrival=null;state.worldCamera=null;state.location='town';state.mapSel='town';render();});assert.equal(await p.locator('[data-map-zoom]').count(),0);assert.equal(await p.locator('[data-loc] text').count(),0);
 const f=await p.locator('.map-frame').boundingBox(),x=f.x+f.width/2,y=f.y+f.height/2,old=await p.evaluate(()=>({...state.worldCamera.cam}));await p.mouse.move(x,y);await p.mouse.down();await p.mouse.move(x+35,y+60,{steps:8});await p.mouse.up();const moved=await p.evaluate(()=>({...state.worldCamera.cam}));assert.notEqual(old.x,moved.x);assert.notEqual(old.y,moved.y);assert.equal(await p.evaluate(()=>state.travel),null);await p.waitForTimeout(550);
 await p.evaluate(()=>focusWorldParty(WORLD.locations.find(l=>l.id==='forest')));await p.locator('[data-loc="forest"]').hover();assert(await p.locator('#world-place-hint').isVisible());assert.match(await p.locator('#world-place-hint').innerText(),/森林/);await p.screenshot({path:shots+'/map-hover.png'});await p.evaluate(()=>Math.random=()=>.9);await p.locator('[data-loc="forest"]').click();assert.equal(await p.evaluate(()=>state.travel.to),'forest');
 // All four can fail once, used buttons disabled, no early continue/no money.
 await setup(p,{tier:4});const baseline=await p.evaluate(()=>({...state.gold}));await p.evaluate(()=>resumeWorldTravel());assert.equal(await p.evaluate(()=>state.page),'story');
 for(const id of ['wolf','raccoon','tiger','fox']){
  await p.evaluate(()=>Math.random=()=>0);await p.locator(`[data-chest-pick="${id}"]`).click();assert.equal(await p.evaluate(()=>state.worldChest.attempts.at(-1).roll),1);assert(await p.locator('.check-row').isVisible());await advance(p);assert.equal(await p.locator(`[data-info="${id}"] .story-critter-mark`).count(),1);if(id==='wolf'){await p.waitForTimeout(450);await p.screenshot({path:shots+'/failure.png'});}await advance(p);
  if(id!=='fox'){assert(await p.locator(`[data-chest-pick="${id}"]`).isDisabled());const n=await p.evaluate(()=>state.worldChest.attempts.length);await p.evaluate(id=>worldChestPick(id,20),id);assert.equal(await p.evaluate(()=>state.worldChest.attempts.length),n);}
 }
 assert.equal(await p.evaluate(()=>state.worldChest.status),'failed');assert.deepEqual(await p.evaluate(()=>state.gold),baseline);assert(await p.locator('#resumeWorldTravel').isEnabled());const at=await p.evaluate(()=>state.travel.t);await p.locator('#resumeWorldTravel').click();assert.equal(await p.evaluate(()=>state.page),'map');assert((await p.evaluate(()=>state.travel.t))>=at&&(await p.evaluate(()=>state.travel.t))<at+.03);await p.evaluate(()=>state.travel.paused=true);
 // Every character's DEX DC boundary, rarity/gold bounds, no reroll/duplicate payment.
 const cases=await p.evaluate(()=>{
  const result=[];
  for(let i=0;i<5;i++)for(const edge of [0,.999999]){const values=[(i+.1)/5,edge,.5];const e=createWorldChest(()=>values.shift());result.push({tier:i,gold:e.gold,dc:e.dc,rarity:e.rarity,mimic:e.mimic});}
  return result;
 });assert.deepEqual(await p.evaluate(()=>[.099999,.1].map(x=>{const a=[.5,.5,x];return createWorldChest(()=>a.shift()).mimic;})),[true,false]);for(const c of cases){const ranges=[[100,200],[200,300],[300,400],[400,500],[500,600]];assert(c.gold>=ranges[c.tier][0]&&c.gold<=ranges[c.tier][1]);assert.equal(c.mimic,false);}
 for(const id of ['fox','tiger','wolf','raccoon']){
  await setup(p);const gold=await p.evaluate(()=>({...state.gold})),m=await p.evaluate(id=>modOf(finalScore(id,'DEX')),id);
  await p.evaluate(({id,r})=>worldChestPick(id,r),{id,r:10-m});assert.equal(await p.evaluate(()=>state.worldChest.status),'opened');assert.equal(await p.locator('[data-chest-pick]').count(),0);
  for(const other of ['fox','tiger','wolf','raccoon'])assert.equal((await p.evaluate(()=>state.gold))[other]-gold[other],175);
  const snapshot=await p.evaluate(()=>JSON.stringify(state.worldChest));await p.evaluate(id=>{worldChestPick(id,1);render();},id);assert.equal(await p.evaluate(()=>JSON.stringify(state.worldChest)),snapshot);await advance(p);assert.equal(await p.locator('.chest-lid').getAttribute('transform'),'translate(-7 -36) rotate(-15)');assert.equal(await p.locator(`[data-info="${id}"] .story-critter-mark`).count(),1);if(id==='raccoon'){await p.waitForTimeout(450);await p.screenshot({path:shots+'/success.png'});}
  await setup(p);await p.evaluate(({id,r})=>worldChestPick(id,r),{id,r:9-m});assert.equal(await p.evaluate(()=>state.worldChest.status),'locked');
 }
 // Mimic reveal on first touch, saved identity, genuine existing AI and attack, retry, original route.
 await setup(p,{tier:2,mimic:true});const money=await p.evaluate(()=>({...state.gold})),trip=await p.evaluate(()=>JSON.stringify(state.travel)),caravan=await p.evaluate(()=>JSON.stringify(state.caravan));await p.locator('[data-chest-pick="tiger"]').click();while(await p.evaluate(()=>state.line<worldChestScript().length-1))await advance(p);assert.equal(await p.locator('.story-chest .mimic-token').count(),1);assert.equal(await p.locator('#map-party').count(),0);await p.waitForTimeout(550);await p.screenshot({path:shots+'/mimic-reveal.png'});await p.locator('#startWorldMimic').click();assert.equal(await p.evaluate(()=>B().id),'worldMimic');assert(await p.locator('.board .mimic-token').count());assert.deepEqual(await p.evaluate(()=>state.gold),money);
 await p.evaluate(()=>{B().flowEpoch=(B().flowEpoch||0)+1;B().result='lose';refreshBattle();});const event=await p.evaluate(()=>JSON.stringify(state.worldChest));await p.locator('#retry').click();assert.equal(await p.evaluate(()=>JSON.stringify(state.worldChest)),event);assert.equal(await p.evaluate(()=>B().units.find(u=>u.side==='foe').rarity),'rare');
 await p.evaluate(()=>{const b=B();b.flowEpoch=(b.flowEpoch||0)+1;const e=b.units.find(u=>u.side==='foe');e.x=6;e.y=5;b.turn=b.units.indexOf(e);beginTurn(e);b.busy=false;Math.random=()=>.99;aiTurn(e);});await p.waitForFunction(()=>B().units.find(u=>u.side==='foe').testSkillUsed);assert(await p.evaluate(()=>B().log.some(l=>JSON.stringify(l).includes('撞倒'))));assert(await p.evaluate(()=>B().units.some(u=>u.side==='pc'&&u.hp<u.maxHp)));
 await p.evaluate(()=>{const b=B();b.flowEpoch=(b.flowEpoch||0)+1;const e=b.units.find(u=>u.side==='foe'),u=b.units.find(u=>u.id==='tiger');e.x=6;e.y=6;u.x=7;u.y=6;b.turn=b.units.indexOf(u);beginTurn(u);b.busy=false;Math.random=()=>.99;refreshBattle();centerCam(6,5);});await p.waitForTimeout(1100);await p.waitForFunction(()=>!B().critOn);await p.screenshot({path:shots+'/mimic-battle.png'});
 await p.locator('.token[data-moving-unit="foe0"]').click();assert.equal(await p.locator('.inf-doll .mimic-token').count(),1);await p.locator('[data-closeinfo]').click();
 const retained=await p.evaluate(()=>{const floor=document.getElementById('board-floor'),e=B().units.find(u=>u.side==='foe');e.rarity='legendary';refreshBattle();const color=document.querySelector('.board .mimic-token .chest-lock').getAttribute('fill'),same=document.getElementById('board-floor')===floor;e.rarity='rare';refreshBattle();return {color,same};});assert.equal(retained.color,'#e6b94e');assert(retained.same);

 const key=await p.evaluate(()=>unitSkills(cur()).find(s=>s.def.basicAttack||(s.idx===0&&s.def.kind==='近戰')).key);await p.locator('[data-cmd="act"]:visible').click();await p.locator(`[data-skill="${key}"]:visible`).click();await p.locator('.token[data-moving-unit="foe0"]').click();if(await p.locator('[data-aim="cast"]').count())await p.locator('[data-aim="cast"]').click();await p.waitForFunction(()=>B().result==='win');assert.match(await p.locator('#afterWin').innerText(),/繼續/);await p.locator('#afterWin').click();assert.equal(await p.evaluate(()=>state.worldChest.status),'defeated');assert.equal(await p.evaluate(()=>JSON.stringify(state.travel)),trip);assert.equal(await p.evaluate(()=>JSON.stringify(state.caravan)),caravan);assert.deepEqual(await p.evaluate(()=>state.gold),money);await advance(p);await p.locator('#resumeWorldTravel').click();assert((await p.evaluate(()=>state.travel.t))>=.56&&(await p.evaluate(()=>state.travel.t))<.59);await p.evaluate(()=>state.travel.paused=true);
 // Actual mobile first/second tap, vertical swipe, pinch; gestures never navigate.
 const mobile=await open(true);await mobile.evaluate(()=>{state.page='map';state.worldCamera=null;render();focusWorldParty(WORLD.locations.find(l=>l.id==='forest'));});await mobile.locator('[data-loc="forest"]').tap();assert.equal(await mobile.evaluate(()=>state.travel),null);assert(await mobile.locator('#world-place-hint').isVisible());await mobile.evaluate(()=>Math.random=()=>.9);await mobile.locator('[data-loc="forest"]').tap();assert.equal(await mobile.evaluate(()=>state.travel.to),'forest');await mobile.evaluate(()=>{state.travel=null;state.location='town';state.mapSel='town';state.worldCamera=null;render();});const box=await mobile.locator('.map-frame').boundingBox(),cdp=await mobile.context().newCDPSession(mobile),before=await mobile.evaluate(()=>state.worldCamera.cam.y);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:box.x+120,y:box.y+180,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:box.x+140,y:box.y+240,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.notEqual(await mobile.evaluate(()=>state.worldCamera.cam.y),before);assert.equal(await mobile.evaluate(()=>state.travel),null);
 const z=await mobile.evaluate(()=>state.worldCamera.zoom);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:box.x+110,y:box.y+170,id:1},{x:box.x+200,y:box.y+170,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:box.x+70,y:box.y+170,id:1},{x:box.x+250,y:box.y+170,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert((await mobile.evaluate(()=>state.worldCamera.zoom))>z);assert.equal(await mobile.evaluate(()=>state.travel),null);
 assert.equal(downloads.length,0);assert.deepEqual(errors,[]);console.log('✓ blue selection/drag disabled, town supplier background, default XY drag, no +/- or labels, hover+click/touch preview+go, 5 DC/gold tiers, all four attempts, disabled duplicates, success/failure/dice/moods, one-time split reward, no reroll, mimic reveal/AI/topple/retry/combat victory/original trip, mobile swipe/pinch, zero new images, screenshots');
}catch(e){console.error('Browser errors:',errors);for(const c of browser.contexts())for(const p of c.pages())console.error(await p.evaluate(()=>({body:document.body.className,text:document.body.innerText.slice(0,200),failures:typeof entryImageFailures!=='undefined'?[...entryImageFailures]:[]})));throw e;}finally{await browser.close();server.close();}
