import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import http from 'node:http';import {chromium} from 'playwright';
const requests=[],errors=[],root=process.cwd(),shots=process.env.WORLD_SHOTS||'/tmp/world-review';await fs.mkdir(shots,{recursive:true});
const server=http.createServer(async(req,res)=>{try{const f=path.join(root,new URL(req.url,'http://local').pathname);res.setHeader('Content-Type',f.endsWith('.js')?'text/javascript':f.endsWith('.css')?'text/css':f.endsWith('.webp')?'image/webp':'text/html');res.end(await fs.readFile(f));}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch();
try{
 const p=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});await p.addInitScript(()=>{window.NO_LUCK_ASK=true;});p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(/\.webp/.test(r.url()))requests.push(r.url());});await p.route('https://fonts.googleapis.com/**',r=>r.abort());await p.addInitScript(()=>localStorage.setItem('fuwa-help-seen','{"map":1,"shop":1}'));
 await p.goto(`http://127.0.0.1:${server.address().port}/index.html#town`);await p.locator('[data-town-place="inn"]').waitFor();const initial=requests.length;
 await p.locator('[data-town-place="inn"]').tap();await p.locator('#townAction').tap();assert.equal(await p.locator('.town-service-page .quip-face').count(),1);assert.equal(await p.locator('.town-service-page .actor').count(),0);await p.locator('[data-rest-who="wolf"]').tap();assert.equal(await p.evaluate(()=>state.townRest.restWho),'wolf');await p.locator('#shortRest').tap();assert.equal(await p.evaluate(()=>state.shortRestsUsed),1);await p.locator('#longRest').tap();assert.equal(await p.evaluate(()=>state.shortRestsUsed),0);assert.equal(await p.evaluate(()=>state.scene),'innRest');await p.evaluate(()=>{state.page='town';state.townPlace='inn';state.townPanel='rest';render();});await p.screenshot({path:shots+'/inn.png'});assert((await p.locator('#townStreet').boundingBox()).y<844);
 await p.locator('#townStreet').tap();await p.locator('[data-town-place="guild"]').tap();await p.locator('#townAction').tap();assert.match(await p.locator('.quest-board').innerText(),/委託板/);await p.screenshot({path:shots+'/guild.png'});await p.locator('#townServiceBack').tap();assert.equal(await p.locator('#townAction').count(),1);
 await p.evaluate(()=>{state.page='story';state.scene='townArrival';state.line=0;render();});await p.waitForTimeout(500);const stage=await p.locator('.stage').boundingBox(),party=await p.locator('.party').boundingBox();await p.evaluate(()=>{state.page='map';state.mapSel='town';state.worldCamera=null;render();});await p.waitForTimeout(500);const map=await p.locator('.map-frame').boundingBox(),mapParty=await p.locator('.party').boundingBox();assert(Math.abs(map.height-stage.height)<1);assert(Math.abs(mapParty.y-party.y)<1);assert.equal(await p.locator('#map-terrain image').count(),1);assert.equal(await p.locator('#map-places image').count(),4);assert.equal(await p.locator('#map-roads path').count(),6);await p.screenshot({path:shots+'/map.png'});
 const old=await p.evaluate(()=>JSON.stringify(state.worldCamera));await p.locator('.map-frame').hover();await p.mouse.wheel(0,-150);await p.waitForTimeout(100);assert.notEqual(await p.evaluate(()=>JSON.stringify(state.worldCamera)),old);
 const box=await p.locator('.map-frame').boundingBox(),sel=await p.evaluate(()=>state.mapSel);await p.mouse.move(box.x+box.width/2,box.y+box.height/2);await p.mouse.down();await p.mouse.move(box.x+box.width/2+80,box.y+box.height/2-45,{steps:8});await p.mouse.up();assert.equal(await p.evaluate(()=>state.mapSel),sel);assert.equal(await p.evaluate(()=>state.travel),null);
 // Actual two-touch pinch via CDP, independent of zoom buttons.
 const cdp=await p.context().newCDPSession(p),touch=(type,a,b)=>cdp.send('Input.dispatchTouchEvent',{type,touchPoints:type==='touchEnd'?[]:[{x:a,y:box.y+150,id:1},{x:b,y:box.y+150,id:2}]});const before=await p.evaluate(()=>state.worldCamera.zoom);await touch('touchStart',box.x+100,box.x+180);await touch('touchMove',box.x+70,box.x+220);await touch('touchEnd');assert((await p.evaluate(()=>state.worldCamera.zoom))>before);
 assert.deepEqual(await p.evaluate(()=>worldRoute('forest','cave')),['forest','town','cave']);
 await p.evaluate(()=>{Math.random=()=>.9;beginWorldTravel('forest');window.__mapTerrain=document.getElementById('map-terrain');window.__worldHeads=[...document.querySelectorAll('#map-party .pf')];});await p.waitForTimeout(500);assert(await p.evaluate(()=>document.getElementById('map-terrain')===window.__mapTerrain&&window.__worldHeads.every((el,i)=>el===document.querySelectorAll('#map-party .pf')[i])));await p.locator('#worldStop').tap();const stopped=await p.evaluate(()=>state.travel.t);await p.waitForTimeout(500);assert.equal(await p.evaluate(()=>state.travel.t),stopped);await p.locator('#worldStop').tap();await p.waitForFunction(()=>!!state.worldLine);await p.screenshot({path:shots+'/banter.png'});assert(await p.locator('.world-banter').count());await p.locator('[data-info="fox"]').tap();assert.equal(await p.locator('[role="dialog"]').count(),1);await p.getByRole('button',{name:'關閉',exact:true}).tap();await p.waitForFunction(()=>!!state.worldArrival);assert.equal(await p.evaluate(()=>state.location),'forest');await p.locator('#worldSkip').tap();await p.locator('#worldEnter').tap();assert.match(await p.locator('#map-message').innerText(),/探索待製作/);
 // Force chest choice only, travel/alert/story/resume run through real timers.
 const gold=await p.evaluate(()=>JSON.stringify(state.gold));await p.evaluate(()=>{Math.random=()=>0;beginWorldTravel('cave');});await p.waitForFunction(()=>state.travel?.alert);assert.deepEqual(await p.locator('#map-party .c-head').evaluateAll(es=>es.map(e=>e.src.split('/').at(-1))),await p.evaluate(()=>CRITTERS.map(c=>sceneAssetURL(critterFaceSrc(c.id,c.id==='tiger'?'blank':'surprised')).split('/').at(-1))));assert.equal(await p.locator('#map-party .story-critter-mark').count(),4);await p.waitForTimeout(500);await p.screenshot({path:shots+'/surprise.png'});const travelT=await p.evaluate(()=>state.travel.t);await p.locator('.map-frame').hover();await p.mouse.wheel(0,-150);await p.waitForTimeout(100);assert.equal(await p.evaluate(()=>state.travel.t),travelT);await p.waitForFunction(()=>state.scene==='worldChest'&&state.page==='story');assert.equal(await p.locator('.story-chest .explore-chest').count(),1);await p.waitForTimeout(500);await p.screenshot({path:shots+'/chest.png'});
 for(let i=0;i<5;i++){await p.locator('#stage').tap();await p.waitForFunction(n=>state.line===n+1,i);}await p.evaluate(()=>state.worldChest.mimic=false);for(const id of ['fox','tiger','wolf','raccoon']){await p.locator(`[data-chest-pick="${id}"]`).tap();for(let j=0;j<2;j++){const n=await p.evaluate(()=>state.line);await p.locator('#stage').tap();await p.waitForFunction(n=>state.line===n+1,n);}}await p.locator('#resumeWorldTravel').tap();await p.waitForFunction(()=>!!state.worldArrival);assert.equal(await p.evaluate(()=>state.location),'cave');assert.equal(await p.evaluate(()=>JSON.stringify(state.gold)),gold);assert.equal(await p.evaluate(()=>state.worldArrival.done),false);
 // Repeat arrival is short; chest rolls once per full departure, no reroll on resume.
 await p.evaluate(()=>{state.worldArrival=null;state.location='town';state.mapSel='town';Math.random=()=>.9;render();beginWorldTravel('cave');});await p.waitForFunction(()=>!!state.worldArrival);assert.equal(await p.evaluate(()=>state.worldArrival.done),true);
 // Original caravan trigger remains automatic and no random chest involved.
 await p.evaluate(()=>{state.worldArrival=null;state.travel={from:'tavern',to:'town',t:.49,stop:.5,alert:false};state.page='map';render();startTravel();});await p.waitForFunction(()=>state.travel?.alert);assert.equal(await p.locator('#map-party .story-critter-mark').count(),4);await p.waitForFunction(()=>state.page==='story'&&state.scene==='ambush');

 // Returning to the tavern after rescue must not repeat the first ambush.
 await p.evaluate(()=>{state.travel=null;state.worldArrival=null;state.page='story';state.scene='farewell';state.line=FAREWELL.length-1;render();});await p.locator('#toMap').tap();assert.equal(await p.evaluate(()=>state.travel),null);
 // Battle uses the extracted camera math too: real touch drag and pinch, same scene layers.
 await p.evaluate(()=>{window.setTimeout=()=>0;window.setInterval=()=>0;quickBattle();B().tut=-1;B().busy=false;render();});await p.waitForTimeout(500);const bcam=await p.evaluate(()=>({...B().cam}));
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:170,y:340}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:210,y:380}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert(await p.evaluate(old=>B().cam.x!==old.x||B().cam.y!==old.y,bcam));
 const bz=await p.evaluate(()=>camZoom());await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:130,y:350,id:1},{x:230,y:350,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:100,y:350,id:1},{x:260,y:350,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert((await p.evaluate(()=>camZoom()))>bz);assert(await p.evaluate(()=>['board-floor','board-marks','board-scene'].every(id=>document.getElementById(id).closest('.board')===document.querySelector('.board'))));
 assert.equal(requests.length,initial,'boot-preloaded assets must cause zero new downloads');assert.deepEqual(errors,[]);console.log('✓ 390×844 shared inn/guild, story stage/party height, five art layers, drag/zoom/pinch, pause, road routing, banter, arrival/skip/revisit, chest surprise/story/four failed attempts/resume/no rewards/no reroll, automatic caravan, zero new image downloads');
}finally{await browser.close();server.close();}
